FROM python:3.12-slim

RUN pip install fastapi \
                uvicorn \
                transformers \
                torch \
                sentencepiece \
                accelerate \
                llama-cpp-python \
                --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu

WORKDIR /

CMD ["python", "internals/server.py"]
