FROM python:3.12-slim

WORKDIR /test

RUN pip install fastapi \
                uvicorn \
                transformers \
                torch \
                sentencepiece \
                accelerate

COPY internals/ internals/


CMD ["python", "internals/server.py"]
